# UMNI OT Configuration
set(UMNI_DEVICE_NAME "UMNI OT")

set(UMNI_FW_VERSION_MAJOR 1)
set(UMNI_FW_VERSION_MINOR 0)
set(UMNI_FW_VERSION_PATCH 0)
set(UMNI_FW_VERSION "${UMNI_FW_VERSION_MAJOR}.${UMNI_FW_VERSION_MINOR}.${UMNI_FW_VERSION_PATCH}")

# Features
set(UM_FEATURE_ETH ON)
set(UM_FEATURE_OT ON)
set(UM_FEATURE_OW OFF)
set(UM_FEATURE_NTC1 ON)
set(UM_FEATURE_NTC2 ON)
set(UM_FEATURE_SD OFF)

# Pins (пример - подставьте реальные)
set(UM_CFG_OT_IN 16)
set(UM_CFG_OT_OUT 17)
set(UM_CFG_ONEWIRE_PIN 4)